<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>Contact</pageOrSobjectType>
    </actionOverrides>
    <actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>Contact</pageOrSobjectType>
    </actionOverrides>
    <brand>
        <headerColor>#0070D2</headerColor>
        <shouldOverrideOrgTheme>false</shouldOverrideOrgTheme>
    </brand>
    <formFactors>Small</formFactors>
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <isOmniPinnedViewEnabled>false</isOmniPinnedViewEnabled>
    <label>Customer Data Cloud</label>
    <navType>Console</navType>
    <tabs>standard-Contact</tabs>
    <tabs>xDO_MDC_Custom_Activity__c</tabs>
    <tabs>xDO_MDC_Unified_Addresses__c</tabs>
    <tabs>xDO_MDC_Unified_Link__c</tabs>
    <tabs>xdo_dc_Timeline_Activity__c</tabs>
    <tabs>xdo_dc_universal_360__c</tabs>
    <uiType>Lightning</uiType>
    <utilityBar>Customer_Data_Cloud_UtilityBar</utilityBar>
    <workspaceConfig>
        <mappings>
            <tab>standard-Contact</tab>
        </mappings>
        <mappings>
            <tab>xDO_MDC_Custom_Activity__c</tab>
        </mappings>
        <mappings>
            <tab>xDO_MDC_Unified_Addresses__c</tab>
        </mappings>
        <mappings>
            <tab>xDO_MDC_Unified_Link__c</tab>
        </mappings>
        <mappings>
            <tab>xdo_dc_Timeline_Activity__c</tab>
        </mappings>
        <mappings>
            <tab>xdo_dc_universal_360__c</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
